import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class AmenitiesService {
  amenities: Array<string> = [
    'Bathtub',
    'Hair dryer',
    'Cleaning products',
    'Shampoo',
    'Conditioner',
    'Body soap',
    'Bidet',
    'Hot water',
    'Shower gel',
    'EssentialsTowels, bed sheets, soap, and toilet paper',
    'Hangers',
    'Bed linens',
    'Room-darkening shades',
    'Safe',
    'Sound system',
    'Books and reading material',
    'Central air conditioning',
    'Heating',
    'Security cameras on propertyAbbiamo delle telecame…loro privacy rimanendo però al sicuro 24h su 24. ',
    'Wifi',
    'Refrigerator',
    'Mini fridge',
    'Coffee maker',
    'Private entranceSeparate street or building entrance',
    'Private patio or balcony',
    'Private backyard – Fully fencedAn open space on the property usually covered in grass',
    'Fire pit',
    'Outdoor furniture',
    'Outdoor dining area',
    'Free parking on premises',
    'Free street parking',
    'Private hot tub - available all year',
    'Single level homeNo stairs in home',
    'Long term stays allowedAllow stay for 28 days or more',
    'Host greets you',
    'Unavailable: KitchenKitchen',
    'Unavailable: TVTV',
    '2 Fully-equipped kitchens with breakfast bars',
    'Pod espresso machine',
    'Wine fridge',
    'Dishwasher',
    'Ice maker ',
    'Satellite television',
    'Smart television',
    'Integrated sound system',
    'Wi-Fi',
    'Air conditioning',
    'Washer & Dryer',
    'Iron/Ironing board',
    'River view',
    'Essentials',
    'Extra pillows and blankets',
    'TV',
    'Crib',
    'Pack ’n play/Travel crib',
    'Children’s books and toys',
    'Indoor fireplace: wood-burning',
    'Smoke alarm',
    'Fire extinguisher',
    'First aid kit',
    'Kitchen',
    'Cooking basics',
    'Dishes and silverware',
    'Other electric stove',
    'Wine glasses',
    'Toaster',
    'Barbecue utensils',
    'Washer',
    'Iron',
    'Dedicated workspace',
    'Private entrance',
    'BBQ grill',
    'Self check-in',
    'Building staff',
    'Long term stays allowed',
    'Unavailable: Security cameras on propertySecurity cameras on property',
    'Unavailable: Smoke alarmSmoke alarm',
    'Unavailable: Carbon monoxide alarmCarbon monoxide alarm',
    'Free washer – In unit',
    'Drying rack for clothing',
    'Clothing storage: closet',
    'AC - split type ductless system',
    'Central heating',
    'Security cameras on propertyClearly labelled SECUR…stalled on the OUTSIDE PERIMETER of the property.',
    'KitchenSpace where guests can cook their own meals',
    'Microwave',
    'Cooking basicsPots and pans, oil, salt and pepper',
    'Dishes and silverwareBowls, chopsticks, plates, cups, etc.',
    'Electric stove',
    'Hot water kettle',
    'Coffee maker: french press',
    'Coffee',
    'Dining table',
    'Shared patio or balcony',
    'Paid street parking off premises',
    'Luggage dropoff allowedFor guests',
    'convenience when they have early arrival or late departure',
  ];
  constructor() {}
}
